In [71]:
import numpy as np
import pandas as pd

In [73]:
df=pd.read_csv("ipl_sample.csv")
df

       player_name  player_age team      venue   player_role
0      Virat Kohli        35.0  RCB  Bengaluru       Batsman
1     Rohit Sharma        37.0   MI     Mumbai       Batsman
2   Jasprit Bumrah        31.0   MI     Mumbai        Bowler
3         MS Dhoni         NaN  CSK    Chennai  Wicketkeeper
4  Ravindra Jadeja        36.0  NaN    Chennai    Allrounder
5    Hardik Pandya        32.0   MI        NaN    Allrounder
6         KL Rahul         NaN  LSG    Lucknow       Batsman
7     Shubman Gill        26.0   GT  Ahmedabad       Batsman
8   Mohammed Shami         NaN   GT  Ahmedabad        Bowler
9  Ruturaj Gaikwad        28.0  CSK    Chennai       Batsman

In [75]:
df.isnull().sum()

player_name    0
player_age     3
team           1
venue          1
player_role    0
dtype: int64

In [81]:
#df[["player_age"]]=df[["player_age"]].fillna(df["player_age"].median())
df

       player_name  player_age team      venue   player_role
0      Virat Kohli        35.0  RCB  Bengaluru       Batsman
1     Rohit Sharma        37.0   MI     Mumbai       Batsman
2   Jasprit Bumrah        31.0   MI     Mumbai        Bowler
3         MS Dhoni        32.0  CSK    Chennai  Wicketkeeper
4  Ravindra Jadeja        36.0  NaN    Chennai    Allrounder
5    Hardik Pandya        32.0   MI        NaN    Allrounder
6         KL Rahul        32.0  LSG    Lucknow       Batsman
7     Shubman Gill        26.0   GT  Ahmedabad       Batsman
8   Mohammed Shami        32.0   GT  Ahmedabad        Bowler
9  Ruturaj Gaikwad        28.0  CSK    Chennai       Batsman

In [89]:
###Suppose the 'team' column in your IPL dataset contains missing values.Replace all missing
###team names with the constant value 'Unknown' and print the first 10 rows.
df[["team"]]=df[["team"]].fillna("unknown")
df.head(10)

       player_name  player_age     team      venue   player_role
0      Virat Kohli        35.0      RCB  Bengaluru       Batsman
1     Rohit Sharma        37.0       MI     Mumbai       Batsman
2   Jasprit Bumrah        31.0       MI     Mumbai        Bowler
3         MS Dhoni        32.0      CSK    Chennai  Wicketkeeper
4  Ravindra Jadeja        36.0  unknown    Chennai    Allrounder
5    Hardik Pandya        32.0       MI        NaN    Allrounder
6         KL Rahul        32.0      LSG    Lucknow       Batsman
7     Shubman Gill        26.0       GT  Ahmedabad       Batsman
8   Mohammed Shami        32.0       GT  Ahmedabad        Bowler
9  Ruturaj Gaikwad        28.0      CSK    Chennai       Batsman

In [93]:
###Take the 'venue' column (categorical) from your IPL dataset and apply one-hot encoding using
### pandas' get_dummies(). Show the resulting DataFrame with the new columns.
venue_encoded = pd.get_dummies(df, columns=['venue'])
print(venue_encoded)

       player_name  player_age     team   player_role  venue_Ahmedabad  \
0      Virat Kohli        35.0      RCB       Batsman            False
1     Rohit Sharma        37.0       MI       Batsman            False
2   Jasprit Bumrah        31.0       MI        Bowler            False
3         MS Dhoni        32.0      CSK  Wicketkeeper            False
4  Ravindra Jadeja        36.0  unknown    Allrounder            False
5    Hardik Pandya        32.0       MI    Allrounder            False
6         KL Rahul        32.0      LSG       Batsman            False
7     Shubman Gill        26.0       GT       Batsman             True
8   Mohammed Shami        32.0       GT        Bowler             True
9  Ruturaj Gaikwad        28.0      CSK       Batsman            False

   venue_Bengaluru  venue_Chennai  venue_Lucknow  venue_Mumbai
0             True          False          False         False
1            False          False          False          True
2            False          False          False          True
3            False           True          False         False
4            False           True          False         False
5            False          False          False         False
6            False          False           True         False
7            False          False          False         False
8            False          False          False         False
9            False           True          False         False

In [105]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [109]:
df['player_role_encoded'] = le.fit_transform(df['player_role'])
print(df[['player_role', 'player_role_encoded']])

    player_role  player_role_encoded
0       Batsman                    1
1       Batsman                    1
2        Bowler                    2
3  Wicketkeeper                    3
4    Allrounder                    0
5    Allrounder                    0
6       Batsman                    1
7       Batsman                    1
8        Bowler                    2
9       Batsman                    1

In [113]:
print("\nMapping:")
for i, role in enumerate(le.classes_):
    print(f"{role} -> {i}")
print(le.classes_)

Mapping:
Allrounder -> 0
Batsman -> 1
Bowler -> 2
Wicketkeeper -> 3
['Allrounder' 'Batsman' 'Bowler' 'Wicketkeeper']